#!/bin/bash

conda create -y -n ipykernel_py2 python=2.7 ipykernel
source activate ipykernel_py2
python -m ipykernel install --user
python -m pip install -r newEnvPy2.txt
source deactivate


# Install JupyterLab extension
# jupyter labextension install @jupyterlab/latex
# jupyter lab build
# jupyter labextension install @jupyterlab/toc

# Remove output from Jupyter notebooks
# jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace python_example_for_Jupyter.ipynb
# jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace R_example_for_Jupyter.ipynb

wget -q -O notebooks-godae.zip "https://atlas.mercator-ocean.fr/s/WN2fEpNrH5eQotF/download"
unzip notebooks-godae.zip
