#!/bin/bash

conda create -y -n ipykernel_py2 python=2.7 ipykernel
source activate ipykernel_py2
python -m ipykernel install --user
source deactivate
conda env update -f binder/environment2.yml -n ipykernel_py2

wget -q -O notebooks-godae.zip "https://atlas.mercator-ocean.fr/s/Fb7GrnaE43wGYDd/download"
unzip notebooks-godae.zip
rm -rf notebooks-godae.zip
